# Generated by Django 5.2.9 on 2025-12-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifeDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_yil_dosyasi', models.FileField(upload_to='tarife/eski/')),
                ('yeni_yil_dosyasi', models.FileField(upload_to='tarife/yeni/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
