# Generated by Django 5.2.9 on 2026-01-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifeDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_yil_dosyasi', models.FileField(upload_to='tarifeler/eski/', verbose_name='Eski Yıl Listesi')),
                ('yeni_yil_dosyasi', models.FileField(upload_to='tarifeler/yeni/', verbose_name='Yeni Yıl Listesi')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarife Dosyası',
                'verbose_name_plural': 'Tarife Dosyaları',
            },
        ),
        migrations.CreateModel(
            name='HizmetListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('hizmet_kodu', models.CharField(max_length=50, verbose_name='Hizmet Kodu')),
                ('hizmet_adi', models.TextField(verbose_name='Hizmet Adı')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmet Listesi',
                'unique_together': {('yil', 'hizmet_kodu')},
            },
        ),
        migrations.CreateModel(
            name='TarifeKarsilastirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar_fark', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fark')),
                ('yuzde_degisim', models.FloatField(verbose_name='Yüzde Değişim')),
                ('durum', models.CharField(max_length=50, verbose_name='Durum')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('eski_hizmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eski_karsilastirma_kaydi', to='core.hizmetlistesi', verbose_name='Eski Yıl Hizmeti')),
                ('yeni_hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeni_karsilastirma_kaydi', to='core.hizmetlistesi', verbose_name='Yeni Yıl Hizmeti')),
            ],
            options={
                'verbose_name': 'Tarife Karşılaştırma',
                'verbose_name_plural': 'Tarife Karşılaştırmaları',
            },
        ),
    ]
