# Generated by Django 6.0 on 2025-12-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarifedosyasi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifekarsilastirma',
            name='yeni_hizmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeni_karsilastirma_kaydi', to='core.hizmetlistesi', unique=True, verbose_name='Yeni Yıl Hizmeti'),
        ),
    ]
