# Generated by Django 6.0 on 2025-12-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tarifekarsilastirma_yeni_hizmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifekarsilastirma',
            name='yeni_hizmet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yeni_karsilastirma_kaydi', to='core.hizmetlistesi', verbose_name='Yeni Yıl Hizmeti'),
        ),
    ]
